{% set name = "sphinx-asdf" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f3472b9e70a8a5d41e8b1de39447967fbceae728f7fc897f7379c3dcfa39ecf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.11
    - setuptools
    - pip
    - setuptools_scm
  run:
    - python >=3.11
    - asdf
    - astropy-base >=5.0.4
    - docutils
    - mistune >=3
    - packaging
    - sphinx
    - sphinx-astropy
    - sphinx-rtd-theme
    - toml

test:
  imports:
    - sphinx_asdf
  requires:
    - python >=3.11
    - pip
  commands:
    - pip check

about:
  home: https://github.com/asdf-format/sphinx-asdf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx plugin for generating documentation from ASDF schemas
  doc_url: https://github.com/asdf-format/sphinx-asdf
  dev_url: https://github.com/asdf-format/sphinx-asdf

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - marscher
    - WilliamJamieson
