{% set name = "sphinx-asdf" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0576f9747ed956c10ad45e820454bf73531ad0d66840e29fc1c681d1b27e2913

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - asdf
    - astropy >=5.0.4
    - docutils
    - mistune >=3
    - packaging
    - sphinx
    - sphinx-astropy
    - sphinx-rtd-theme
    - toml
    - python >=3.9

test:
  imports:
    - sphinx_asdf

about:
  home: https://github.com/asdf-format/sphinx-asdf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx plugin for generating documentation from ASDF schemas
  doc_url: https://github.com/asdf-format/sphinx-asdf
  dev_url: https://github.com/asdf-format/sphinx-asdf

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - marscher
    - WilliamJamieson
