{% set name = "sphinx-asdf" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44b3d4829df90bf2f9d0dadfd6a1fe1522c040842cd3c61ff4717edd85d0860e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - asdf
    - astropy >=5.0.4
    - docutils
    - mistune >=3
    - packaging
    - sphinx
    - sphinx-astropy
    - sphinx_bootstrap_theme
    - sphinx-rtd-theme
    - toml
    - python >=3.9

test:
  imports:
    - sphinx_asdf

about:
  home: https://github.com/asdf-format/sphinx-asdf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx plugin for generating documentation from ASDF schemas
  doc_url: https://github.com/asdf-format/sphinx-asdf
  dev_url: https://github.com/asdf-format/sphinx-asdf

extra:
  recipe-maintainers:
    - marscher
    - WilliamJamieson
