{% set name = "sphinx-asdf" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d133be7ba817a4ea81337a7d9541faf985b80d6706a2ad2c981dec5cececa00a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - asdf
    - astropy >=5.0.4
    - docutils
    - graphviz
    - matplotlib-base
    - myst-parser
    - mistune ~=0.8.4
    - sphinx
    - sphinx-astropy
    - sphinx_bootstrap_theme
    - sphinx_rtd_theme
    - sphinx-inline-tabs
    - toml
    - python >=3.6

test:
  imports:
    - sphinx_asdf

about:
  home: https://github.com/asdf-format/sphinx-asdf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx plugin for generating documentation from ASDF schemas
  doc_url: https://github.com/asdf-format/sphinx-asdf
  dev_url: https://github.com/asdf-format/sphinx-asdf

extra:
  recipe-maintainers:
    - marscher
    - WilliamJamieson
